FROM --platform=linux/386 scratch
COPY --from=i686 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/amd64 scratch
COPY --from=x86_64 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/ppc scratch
COPY --from=powerpc . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/ppc64 scratch
COPY --from=powerpc64 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/arm scratch
COPY --from=armv7a . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/arm64 scratch
COPY --from=aarch64 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/riscv32 scratch
COPY --from=riscv32 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]

FROM --platform=linux/riscv64 scratch
COPY --from=riscv64 . /
ENV CROSSLANG_CONTAINER=1
ENTRYPOINT ["/usr/bin/crossint"]