name: Build and Deploy on Tag
on:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_AND_BREW: ${{ secrets.PACKAGE_AND_BREW }} 
  VERSION: ${{ gitea.ref_name }}
  RESULT_IMAGE_NAME: tesses50/crosslang
  GITEA_DOMAIN: git.tesses.org
  GITEA_REGISTRY_USER: tesses50

jobs:
  build-arch:
    runs-on: arch-builder
    steps:
      - uses: actions/checkout@v4
      - run: wget -O /root/repository.key https://git.tesses.org/api/packages/tesses50/arch/repository.key
      - run: pacman-key --add /root/repository.key
      - run: pacman-key --config /opt/cross/ppc/pacman.conf --add /root/repository.key
      - run: printf "[tesses50.git.tesses.org]\nSigLevel = Optional TrustAll\nServer = https://git.tesses.org/api/packages/tesses50/arch/core/\$arch\n" >> /etc/pacman.conf
      - run: printf "[tesses50.git.tesses.org]\nSigLevel = Optional TrustAll\nServer = https://git.tesses.org/api/packages/tesses50/arch/core/\$arch\n" >> /opt/cross/ppc/pacman.conf
      - run: pacman --noconfirm -Sy mbedtls tessesframework zip zig ninja
      - run: pacman --config /opt/cross/ppc/pacman.conf --noconfirm -Sy mbedtls tessesframework
      - run: cp Packaging/Linux/PKGBUILD /home/build/PKGBUILD
      - run: cp Packaging/Linux/build-arch.sh /home/build/build-arch.sh
      - run: chmod 755 /home/build/build-arch.sh
      - run: chown build:build /home/build/PKGBUILD
      - run: chown build:build /home/build/build-arch.sh
      - run: su build -c /home/build/build-arch.sh
      - run: env -C Packaging/Slim bash build.sh
      - uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          prerelease: true
          files: |-
            artifacts/** 
          
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITEA_DOMAIN }}
          username: ${{ env.GITEA_REGISTRY_USER }}
          password: ${{ secrets.PACKAGE_AND_BREW }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  ${{ env.GITEA_DOMAIN }}/${{ env.RESULT_IMAGE_NAME }}:latest
      - uses: actions/checkout@v4
        with:
          ref: "master"
          path: "tapdir"
          repository: "tesses50/tesses-tap.git"
          token: ${{ env.PACKAGE_AND_BREW }}
      - run: |
          cd tapdir
          bash ../Packaging/edit-formula.sh
          git config user.name "Tesses Gitea Bot"
          git config user.email "noreply@tesses.net"
          git add .
          git commit -m "Push crosslang=${{ env.VERSION }}"
          git push