export HASH=`curl https://git.tesses.org/tesses50/crosslang/archive/$VERSION.tar.gz 2> /dev/null | shasum -a 256 | awk '{print $1}'`

echo "class Crosslang < Formula" > "Formula/crosslang.rb"
echo "  desc \"\"" >> "Formula/crosslang.rb"
echo "  homepage \"\"" >> "Formula/crosslang.rb"
echo "  url \"https://git.tesses.org/tesses50/crosslang/archive/$VERSION.tar.gz\"" >> "Formula/crosslang.rb"
echo "  sha256 \"$HASH\"" >> "Formula/crosslang.rb"
echo "  license \"GPLv3\"" >> "Formula/crosslang.rb"
echo "  depends_on \"cmake\" => :build" >> "Formula/crosslang.rb"
echo "  depends_on \"tessesframework\"" >> "Formula/crosslang.rb"
echo "  def install" >> "Formula/crosslang.rb"
echo "    system \"cmake\", \"-S\", \".\", \"-B\", \"build\", \"-DCROSSLANG_FETCHCONTENT=OFF\", *std_cmake_args" >> "Formula/crosslang.rb"
echo "    system \"cmake\", \"--build\", \"build\"" >> "Formula/crosslang.rb"
echo "    system \"cmake\", \"--install\", \"build\"" >> "Formula/crosslang.rb"
echo "  end" >> "Formula/crosslang.rb"
echo "  test do" >> "Formula/crosslang.rb"
echo "    system \"true\"" >> "Formula/crosslang.rb"
echo "  end" >> "Formula/crosslang.rb"
echo "end" >> "Formula/crosslang.rb"