list(APPEND CROSSLANG_SOURCE
src/vm/bc/add.cpp
src/vm/bc/sub.cpp
src/vm/bc/getfield.cpp
src/vm/bc/setfield.cpp
src/vm/bc/tostring.cpp
src/vm/bc/equals.cpp
src/vm/bc/invokemethod.cpp
src/vm/bc/executemethod2.cpp
src/vm/bc/invoketwo.cpp
src/vm/bc/tobool.cpp
src/compiler/codegen.cpp
src/compiler/lexer.cpp
src/compiler/parser.cpp
src/compiler/ast.cpp
src/runtime_methods/uuid.cpp
src/runtime_methods/class.cpp
src/runtime_methods/console.cpp
src/runtime_methods/io.cpp
src/runtime_methods/std.cpp
src/runtime_methods/net.cpp
src/runtime_methods/vm.cpp
src/runtime_methods/json.cpp
src/runtime_methods/sqlite.cpp
src/runtime_methods/dictionary.cpp
src/runtime_methods/crypto.cpp
src/runtime_methods/ogc.cpp
src/runtime_methods/path.cpp
src/runtime_methods/env.cpp
src/runtime_methods/process.cpp
src/runtime_methods/helpers.cpp
src/types/embed.cpp
src/types/async.cpp
src/types/associativearray.cpp
src/types/any.cpp
src/types/ittr.cpp
src/types/closure.cpp
src/types/dictionary.cpp
src/types/externalmethod.cpp
src/types/list.cpp
src/types/native.cpp
src/types/rootenvironment.cpp
src/types/subenvironment.cpp
src/types/vfsheapobject.cpp
src/types/streamheapobject.cpp
src/types/class.cpp
src/types/classenvironment.cpp
src/types/random.cpp
src/types/queryable.cpp
src/vm/filereader.cpp
src/vm/gc.cpp
src/vm/gclist.cpp
src/vm/vm.cpp
src/vm/exception.cpp
src/archive.cpp
src/markedtobject.cpp
src/program_lib/crossarchivecreate.cpp
src/program_lib/crossarchiveextract.cpp
src/program_lib/crossdump.cpp
src/program_lib/crosslang.cpp
src/program_lib/crosslangcompiler.cpp
src/program_lib/crosslanginterperter.cpp
src/program_lib/crosslangvm.cpp
)
